# Generated by Django 4.0 on 2021-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackApp', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackappDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file_doc', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trackApp_document',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
